name: assignment
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
 
 
    - name: Build with Maven
      run: mvn clean install
 
 
    - name: uploading build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar
 
 
    - name: Checkout Artifacts branchgit
      run: |
        git config user.name "pujitha-pie"
        git config user.email "pujitharajeswari.pasula@beehyv.com"
        git checkout -b artefacts-store
        git status
 
  downloading-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Artifacts Branch
      uses: actions/checkout@v4
      with:
        ref: artefacts-store
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar
    - name: Display structure of downloaded files
      run: ls -R  
