name: downloading artifacts
on:
  repository_dispatch:
    types: [trigger-deploy]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_USERNAME: pujitha-pie
      GIT_EMAIL: pujitharajeswari.pasula@beehyv.com
      GIT_BRANCH: master
      COMMIT_MESSAGE: "Adding build artifacts"

    steps:
      - uses: actions/checkout@v4
      
      - name: downloading the artifacts
        uses: actions/download-artifacts@v3
        with:
          name: my-artifacts

      - name: set git configurations
        run: |
            git config --global user.name "${{ env.GIT_USER_NAME }}"
            git config --global user.email "${{ env.GIT_USER_EMAIL }}"
      - name: checking out branch
        run: |
          git checkout -b ${{ env.GIT_BRANCH }} || git checkout ${{ env.GIT_BRANCH }}

      - name: pushing the code
        run: |
          git add .
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push origin main
  
